name: .NET

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Get Data
      run:  WAVaccine/bin/Debug/net5.0/WAVaccine.exe
    - name: Push Data
      run:  |
          git config user.name ChrisJollyAU
          git config user.email actions@github.com
          git add . || exit 0
          git commit -m "Update data" || exit 0
          git push || exit 0
