name: .NET

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Get Data
      run:  WAVaccine/bin/Debug/net5.0/WAVaccine.exe
    - name: Simple commit
      uses: zwaldowski/git-commit-action@v1
      with:
        # Directory to create commit in
        working_directory: .# optional, default is .
        # Commit message
        commit_message: Data update
        # Name to use for commit author
        author_name: Chris
        # Email to use for commit author
        author_email: actions@github.com # optional, default is actions@github.com
